// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBv2fQsykl1DgPsSnKCcVd6Qf8yh8vhoi4',
    appId: '1:603632933825:web:fbe63f109613f0616bad40',
    messagingSenderId: '603632933825',
    projectId: 'agriwatch-pakistan',
    authDomain: 'agriwatch-pakistan.firebaseapp.com',
    storageBucket: 'agriwatch-pakistan.firebasestorage.app',
    measurementId: 'G-09G7RTZ51E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLq7Yjtd6ShlCQixTfTS9fjprTZvjQs6Y',
    appId: '1:603632933825:android:dde030c7928955316bad40',
    messagingSenderId: '603632933825',
    projectId: 'agriwatch-pakistan',
    storageBucket: 'agriwatch-pakistan.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVy2qwtFQ92O5hVKJ5AXbkF0Bqv_70Kf4',
    appId: '1:603632933825:ios:a9e473b0f5c2a7ee6bad40',
    messagingSenderId: '603632933825',
    projectId: 'agriwatch-pakistan',
    storageBucket: 'agriwatch-pakistan.firebasestorage.app',
    iosBundleId: 'com.example.agriwatch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVy2qwtFQ92O5hVKJ5AXbkF0Bqv_70Kf4',
    appId: '1:603632933825:ios:a9e473b0f5c2a7ee6bad40',
    messagingSenderId: '603632933825',
    projectId: 'agriwatch-pakistan',
    storageBucket: 'agriwatch-pakistan.firebasestorage.app',
    iosBundleId: 'com.example.agriwatch',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBv2fQsykl1DgPsSnKCcVd6Qf8yh8vhoi4',
    appId: '1:603632933825:web:c9caedd1155365466bad40',
    messagingSenderId: '603632933825',
    projectId: 'agriwatch-pakistan',
    authDomain: 'agriwatch-pakistan.firebaseapp.com',
    storageBucket: 'agriwatch-pakistan.firebasestorage.app',
    measurementId: 'G-48VDSWTMX1',
  );
}
